'use client';
import {useState} from 'react';
const nav=[['dashboard','⌂','Dashboard'],['patients','◉','Patients'],['alerts','⚠','Vital alerts'],['records','▣','Records & AI'],['rx','℞','Prescriptions'],['medicines','✚','Medicine catalogue'],['nutrition','🥗','Nutrition'],['programmes','▦','Programmes'],['therapies','🧘','Therapies'],['store','▢','Store & orders'],['labs','🧪','Labs & bookings'],['members','◎','Members & plans'],['monitor','◌','Consumption'],['scheduler','◷','Scheduler'],['staff','♙','Roles & SOP'],['ai','✦','AI assistant']];
const patients=[['PT-1042','Priya Raghavan','42 F','Diabetes · HTN','78','Stable'],['PT-1038','Arun Kumar','51 M','Hypertension','71','Review'],['PT-1031','Meena S.','36 F','PCOS · obesity','84','Stable'],['PT-1027','Raghavan V.','47 M','Pre-diabetes','66','Watch']];
export default function AdminWorkspace({displayName='Care team'}:{displayName?:string}){const[active,setActive]=useState('dashboard');return <main className="admin-proto"><header className="admin-top"><div className="admin-brand"><span>LIVYA</span><small>OPERATIONS CONSOLE</small></div><div className="admin-search">⌕&nbsp; Search patients, records, orders or ID</div><div className="admin-who"><span className="notif">3</span><div className="admin-avatar">{displayName.slice(0,2).toUpperCase()}</div><div><b>{displayName}</b><small>Care team · Admin</small></div></div></header><div className="admin-body"><aside className="admin-side"><div className="side-section">CARE OPERATIONS</div>{nav.slice(0,13).map(([id,i,l])=><button key={id} className={active===id?'admin-link on':'admin-link'} onClick={()=>setActive(id)}><span>{i}</span>{l}{id==='alerts'&&<em>3</em>}</button>)}<div className="side-section second">ADMINISTRATION</div>{nav.slice(13).map(([id,i,l])=><button key={id} className={active===id?'admin-link on':'admin-link'} onClick={()=>setActive(id)}><span>{i}</span>{l}</button>)}<div className="admin-foot"><b>● All systems operational</b><small>Supabase · API · AI queue</small></div></aside><section className="admin-main">{active==='dashboard'?<Dashboard setActive={setActive}/>:<Module id={active} setActive={setActive}/>}</section></div></main>}
function Dashboard({setActive}:{setActive:(s:string)=>void}){return <><Head title="Good morning" sub="Here is what needs attention across LIVYA care today." action="＋ New patient"/><div className="admin-kpis"><K l="Active patients" v="1,284" d="+4.2% this month"/><K l="Open vital alerts" v="12" d="3 critical" danger/><K l="Reports to review" v="27" d="8 AI flagged"/><K l="AI jobs today" v="148" d="96% complete"/></div><div className="admin-grid"><section className="admin-panel wide"><Title h="Patients needing attention" p="Prioritised from vitals, records and care-plan activity." action="View all →" onClick={()=>setActive('patients')}/><table><thead><tr><th>Patient</th><th>Condition</th><th>Health</th><th>Signal</th><th>Last activity</th></tr></thead><tbody>{patients.map(p=><tr key={p[0]}><td><b>{p[1]}</b><small>{p[0]} · {p[2]}</small></td><td>{p[3]}</td><td><strong className={p[4]==='66'?'score-low':'score-good'}>{p[4]}</strong></td><td><span className={'tag '+(p[5]==='Stable'?'good':p[5]==='Watch'?'warn':'danger')}>{p[5]}</span></td><td>Today · 9:41 AM</td></tr>)}</tbody></table></section><section className="admin-panel"><Title h="Vital alerts" p="Needs acknowledgement" action="12 open" onClick={()=>setActive('alerts')}/><Alert t="Heart rate high" p="Priya Raghavan · 132 bpm" tm="9:41 AM"/><Alert t="Glucose low" p="Arun Kumar · 64 mg/dL" tm="8:52 AM"/><Alert t="SpO₂ low" p="Meena S. · 89%" tm="8:16 AM"/></section></div><div className="admin-grid"><section className="admin-panel"><Title h="Records & AI review" p="New uploads waiting for clinical review." action="Open queue →" onClick={()=>setActive('records')}/><Queue icon="🧪" text="Lipid profile + HbA1c" meta="Priya Raghavan · AI analysed · 2 Sep" tag="AI ✓"/><Queue icon="📄" text="Discharge summary" meta="Arun Kumar · 3 pages · uploaded 9:12 AM" tag="Review"/><Queue icon="🩻" text="Ultrasound abdomen" meta="Meena S. · AI extraction ready" tag="Review"/></section><section className="admin-panel"><Title h="Today’s care flow" p="Bookings and tasks" action="Scheduler →" onClick={()=>setActive('scheduler')}/><Flow time="09:30" text="Video consultation" meta="Dr. Krishnan · 4 patients"/><Flow time="11:00" text="Report review block" meta="8 records · 2 AI flagged"/><Flow time="15:00" text="Therapy sessions" meta="12 bookings · Anna Nagar"/></section></div></>}
function Head({title,sub,action}:{title:string;sub:string;action:string}){return <div className="admin-heading"><div><span>LIVYA · OPERATIONS</span><h1>{title}</h1><p>{sub}</p></div><button className="red-btn">{action}</button></div>}
function Title({h,p,action,onClick}:{h:string;p:string;action:string;onClick:()=>void}){return <div className="panel-title"><div><h2>{h}</h2><p>{p}</p></div><button onClick={onClick}>{action}</button></div>}
function K({l,v,d,danger=false}:{l:string;v:string;d:string;danger?:boolean}){return <article className="admin-kpi"><span>{l}</span><strong>{v}</strong><small className={danger?'danger-text':''}>{d}</small></article>}
function Alert({t,p,tm}:{t:string;p:string;tm:string}){return <button className="alert-row"><i>!</i><div><b>{t}</b><small>{p}</small></div><time>{tm}</time></button>}
function Queue({icon,text,meta,tag}:{icon:string;text:string;meta:string;tag:string}){return <div className="queue-row"><span>{icon}</span><div><b>{text}</b><small>{meta}</small></div><em>{tag}</em></div>}
function Flow({time,text,meta}:{time:string;text:string;meta:string}){return <div className="flow"><b>{time}</b><div><strong>{text}</strong><small>{meta}</small></div></div>}
function Module({id,setActive}:{id:string;setActive:(s:string)=>void}){const item=nav.find(n=>n[0]===id);return <><Head title={item?.[2]||'Module'} sub="Prototype-matched operational workspace, ready for live Supabase data." action="＋ Create"/><div className="module-hero"><div><span>LIVE MODULE</span><strong>{item?.[2]}</strong><p>Search, filter, review and action patient or operational records without leaving the console.</p></div><b>{id==='patients'?'1,284':id==='alerts'?'12':id==='records'?'27':'Ready'}</b></div><div className="admin-grid"><section className="admin-panel"><h2>Recent activity</h2><Queue icon="🧪" text="Priya Raghavan · record analysed" meta="10 minutes ago · care team" tag="AI ✓"/><Queue icon="⚠" text="Arun Kumar · alert acknowledged" meta="20 minutes ago · care team" tag="Closed"/><Queue icon="▦" text="Meena S. · programme updated" meta="30 minutes ago · care team" tag="Updated"/></section><section className="admin-panel"><h2>Quick actions</h2>{['Review queue','Search patient','Open audit log'].map(x=><button className="quick-admin" key={x}>{x}<b>→</b></button>)}<button className="quick-admin" onClick={()=>setActive('dashboard')}>Back to overview <b>→</b></button></section></div></>}
